### ISSUE TITLE
[FIX] CI fails: virtualenv>=20.27 breaks hatch env creation on GitHub Actions runners

### ISSUE THREAD

**Issue by dariero** [dariero/RagaliQ#66]
## Problem

All CI jobs introduced in #64 fail immediately with:

```
Environment `default` is incompatible: module 'virtualenv.discovery.builtin' has no attribute 'propose_interpreters'
```

## Root Cause

`pip install hatch` on a fresh runner resolves to the latest `virtualenv` (>=20.27.0), which removed the `propose_interpreters` attribute from `virtualenv.discovery.builtin`. Hatch uses this API internally when creating its managed environments. Result: every `hatch run *` command fails before the actual tool runs.

This works locally because existing Hatch envs were created with an older virtualenv and are cached on disk.

## Fix

Remove `hatch run` from CI entirely. GitHub Actions runners already have the correct Python version from `actions/setup-python`. The fix is:

1. `pip install -e ".[dev]"` — installs the project + all dev dependencies into the runner's Python directly
2. Run tools natively: `ruff check src/ tests/`, `mypy src/`, `pytest tests/unit/`

This bypasses Hatch's virtualenv layer completely, makes CI faster (no extra venv creation), and is the standard approach for Python projects in CI.
